### ISSUE TITLE
Error while compiling the Python code with Tensorflow with Nuitka compiler

### ISSUE THREAD

**Issue by swatinair123** [kayhayen/Nuitka#74] opened 2018-04-16 11:33 UTC
Hi,

I am trying to compile a very simple code with tensorflow. which imports tensorflow. The code compiles fine with Pycharm. But when i try comiling with nuitka --recurse-all Tensorflow_test.py . I have installed Nuitka using anaconda prompt
It gives warning Nuitka:WARNING:Tensorflow_test.py:1: Cannot find 'tensorflow' as relative or absolute import.

I tried nuitka --recurse-all --recurse-directory=C:\Users\tier3dlab1\Anaconda2\pkgs\tensorflow-1.2.1-py36_0\Lib\site-packages\tensorflow --show-progress --standalone Tensorflow_test.py this command also where i am giving the path of tensorflow .But it gives me the below error 
File "c:\users\tier3dlab1\anaconda2\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 57, in __init__
    assert '.' not in name, name
AssertionError: benchmark.xcodeproj
and with lots of warnings.
I am able to compile a simple python code with Nuitka. The screenshots are as attached.Please advise
![img1](https://user-images.githubusercontent.com/23516228/38806796-16550d78-4198-11e8-91ea-cacc49b68e5a.jpg)
![imag2](https://user-images.githubusercontent.com/23516228/38806800-1aa1ff4e-4198-11e8-8a86-79aa89bc4ee3.jpg)

**Comment by kayhayen** [comment] 2018-04-18 12:02
Do not use --recurse-directory that way, although it ought to work, but it requires that you do really get right what you are using. However, I can see from the traceback and your PATH that it ought to work.

Can you try calling Nuitka with "python -m nuitka" invocation from your Anaconda Python environment to make sure it isn't that.

I am assuming now there is a ".pth" file that gets in the way of things, or something like this. I will try and reproduce with current Anaconda. Unfortunately you gave no versions for Nuitka, nor Anaconda there. I assume the one included?

**Comment by kayhayen** [comment] 2018-04-18 16:11
Trying to reproduce this on an albeit older Anaconda2:

~/anaconda2/bin/python Mini.py Traceback (most recent call last):
  File "Mini.py", line 1, in <module>
    import tensorflow
ImportError: No module named tensorflow

So, as far as Nuitka goes, everything is fine. If you have PYTHONPATH up to the task, and the python from anaconda itself runs, then use Nuitka. Your PyCharm config is not used.

**Comment by kayhayen** [comment] 2018-04-18 21:43
Well, recursing all of tensorflow clearly isn't possible, it includes "contrib" which is just massive amounts of code. I did however not get the assertion from the import code you did. I believe it may be an indication of you using an older Nuitka version. Please use latest by updating with "conda update nuitka" or so.

**Comment by pratikshaandhare** [comment] 2018-04-20 09:28
Hi,

I am compiling the tensorflow code with Nuitka(version 0.5.28) with
help of anaconda 3 by using command "nuitka --recurse-all predict.py". I am using Python 3.5/3.6. The simple tensorflow code of printing something
is working fine on Nuitka.  But  when I compile some
classification tensorflow code with Nuitka , I  am getting the
warning/error "The filename or extension is too long" where the filename(predict.py) is short. I am saving
.exe file into same folder of the code and .exe file is not
generating.

Here is the screenshot of anaconda prompt. Can you please help me out?

Thanks and regards,
Pratiksha

![nuitkaerror](https://user-images.githubusercontent.com/20615346/39043308-bbb5277a-44aa-11e8-9bbb-99d2e38f37a6.png)

**Comment by kayhayen** [comment] 2018-04-21 09:14
@pratikshaandhare This seems to be a Windows, scons, or compiler issue that I have no clue about.

If I had predict.py I would give it a shot here and see if it happens for me too. Have you tried to have ASCII filenames for the directory you compile in? That is about it.

**Comment by kayhayen** [comment] 2018-04-21 09:15
@swatinair123 No feedback?

**Comment by kayhayen** [comment] 2018-05-11 07:06
Lack and feedback, plus stink of old bug, closing this.

**Closed by kayhayen** 2018-05-11 07:06 UTC

**Comment by cooperdk** [comment] 2018-07-31 03:53
It's not an old bug. I am seeing this too right now, current version of Nuitka and Python...

**Comment by kayhayen** [comment] 2018-07-31 10:08
@cooperdk There is very little that Nuitka can do about this, needs a Scons improvement or so I am thinking. Please consult them.

**Comment by tryzombie501** [comment] 2019-03-16 21:04
Has anyone figured out a work around for this? I'm having this issue when trying to use Nuitka with a discordpy script
