### ISSUE TITLE
Nuitka fails to compile package in current directory if mismatching cases are used in --module and/or --include-package

### ISSUE THREAD

**Issue by baizi2k** [kayhayen/Nuitka#119] opened 2018-09-07 08:46 UTC
hi guys, 
  I tried to complie PyOpengl into .pyd. Errors came up as :  

```
    MainControl.main()
  File "nuitka\MainControl.py", line 800, in main
    filename = filename
  File "nuitka\MainControl.py", line 123, in createNodeTree
    warn           = False
  File "nuitka\importing\Importing.py", line 281, in findModule
    module_name = module_name,
  File "nuitka\importing\Importing.py", line 514, in _findModule
    module_search_cache[key] = _findModule2(module_name)
  File "nuitka\importing\Importing.py", line 544, in _findModule2
    package_name = package_part
  File "nuitka\importing\Importing.py", line 470, in _findModuleInPat
    search_path = search_path
  File "nuitka\importing\Importing.py", line 387, in _findModuleInPat
    for fullname, _filename in listDir(candidate[0]):
  File "nuitka\utils\FileOperations.py", line 78, in listDir
    os.listdir(path)
WindowsError: [Error 3] The system cannot find the path specified: ''
```

So I tried to  get more detail to find out which import failed the complier, so I run nuitka with --verbose under path "C:\python27-x64\Lib\site-packages\OpenGL" :

python -m nuitka --module OpenGL --include-package=openGL --verbose

still, prompt get the same output.   Google can't find any help informations.

Any idea will be most appreciate.

My test Environment:
WIN7x64, python27x64, PyOpengl312cp27, nuitka 0.5.32.7

**Comment by kayhayen** [comment] 2018-09-07 08:53
The use of openGL vs OpenGL strikes me as odd. Can you try with matching case exactly as in filesystem?

The current directory ought to not matter. Nuitka is removing it from import path. You going to site packages dir could cause issues too. Try in homedir too. In fact I expect that to be the issue.

**Comment by brupelo** [comment] 2018-09-07 09:53
@baizi2k I've tried to reproduce your issue and I've managed to build OpenGL succesfully, here's what I did:

 1) `cd d:\virtual_envs\py2714_32\Lib\site-packages`
 2) `nuitka --module OpenGL --include-package=OpenGL --verbose`

As you can see, I use `OpenGL` matching case  exactly in the filesystem and also i just cd into `site-packages`

@kayhayen I've got a question though, I've tried to do the same from a normal directory and I've get this:

    (py2714_32) D:\sources\personal\python\apps\console\pytools\pytools\build\xxx>nuitka --module OpenGL --include-package=OpenGL --verbose
    __main__.py: can't open file 'OpenGL'.

Questions:

 - Any idea about the above issue? It'd be really interesting to build modules from homedir so I won't pollute my virtualenv with build content.
 - Is there any chance to change the name of the final dll? ie: Right now I'll get `OpenGL.pyd` and of course you can't change the name manually as if you did so you'd get the typical `ImportError: dynamic module does not define init function` error message
 - You generate OpenGL.exp, OpenGL.lib and OpenGL.pyi, I dunno what that .pyi file is about but you can instruct cl/link to move the .exp & .lib files into the build folder (they're not necessary for the end user at all as they're not importing the dll on a c project, aren't they?)

**Comment by kayhayen** [comment] 2018-09-07 10:29
Hello there,

yes, stupid me, the --module still packages a filename argument, which can be an absolute file path, whereas the --include-* options take names. Ideally --module would also take a name, but that is something I mean to change, but didn't do yet.

As long as you got all setup so it works for normal Python, you are good. The final extension module is an exact emulation of the module or package. It's name is known to it via "__name__" and you would have to rename the input properly. So there is no chance for that.

That ".exp" and ".lib" file is actually a nice hint for issue #103 where these files end up in the wheel. I am definitely going to solve it that way then. They are indeed useless.

The ".pyi" file lists imported files of your ".pyd", the idea being that somebody using Nuitka later and finding that ".pyi" file can tell what it is importing. So say it does "import something" and that is not included in the package, the ".pyi" file can be used to tell that. It's a standard from the typing craze that some PEP introduced in Python3. 

Do you happen to be the maintainer for this module? Then I would ask you to include the .pyi file. Also, something which is not likely to be working for you yet though, distutils with bdist_nuitka should prodiuce that ".pyd" for you as well. As Nuitka is aiming to become the top choice for C bindings, OpenGL is very interesting for me, and I would want to work with the maintainer clearly.

As for the casing, I will have to reproduce this at home when I have access to Windows. There are some stupid rules for matching cases of modules and filesystem, where exact matches later down the sys.path will win over inexact matcher further up the sys.path, but obviously something bad is happening if  one of the candidates is in current directory, something "dirname" tends to get wrong. That should be fixable, and probably will be in one of the hotfixes or maybe even 0.6 release if I manage.

Thanks for your report. As for the problem I seem to have sufficient input for now.

**Comment by brupelo** [comment] 2018-09-07 11:37
@kayhayen Clear as water, thanks to clarify, if there is that's something to blame here I guess is either the docs are not clear enough or we the users didn't make a proper job trying to follow carefully the provided instructions, for instance, `nuitka --help` says:

    Usage: nuitka [--module] [--run] [options] main_module.py

So I'm guilty here, this was the first time I was trying to build a whole package so I just looked at  @baizi2k  report and I assumed `module name` was expected by `--module`. But clearly in the usage you can see than the expected argument is a path (ie: `main_module.py`). 

If you ask me, having the ability to specify absolute paths is great! I mean, sometimes when coding custom packages I don't have available neither on site-packages (setup.py) nor on any .pth file. So the fact you can use absolute paths to build the package is actually a more flexible way than just using module names... is not? am I missing something here?

Anyway, I think the issue here is trying to improve maybe the user manual and the nuitka help by providing more syntax examples and you're done. For instance, consider the below explanation to an hypothetical user who's getting started with nuitka:

 - In order to build a whole package first make sure you can import the module you want to build. ie: run `python -c "import OpenGL; print(OpenGL)"` and if everything is fine you'll get the module imported and the used path reported `<module 'OpenGL' from 'D:\virtual_envs\py2714_32\lib\site-packages\OpenGL\__init__.pyc'>`
 - The remaining thing is instruct nuitka to build that package, so just use the reported path in the previous step such as `nuitka --include-package=OpenGL --module d:\virtual_envs\py2714_32\lib\site-packages\OpenGL`
 - If everything was fine, you should have a ready-to-go extension module ready to be consumed, enjoy Nuitka! :)

Kay, examples, examples and more examples in the docs ;) This is what makes the difference and what end-users are worried about... End users are worried about optimizations, compilations or details that we developers are, they just want to know how to use the product in a very straightforward way to cover their needs with as little hazzle as possible. For instance, the user manual, you provide 3 different use-cases and talk very briefly about them.... BUT, these 3 use-cases are extremely important to "sell" and explain carefully (with examples), those are the ones end-users are interested about hehe ;) . Does it make sense?

Btw, I've finally compiled pyopengl with both py2.7 and py3.6 and I've got the next total times:

 - Python2.7.14 + vs2015 + nuitka0.5.32.7: Execution time: 822.417 s
 - Python3.6.4 + vs2015 + nuitka0.5.32.7: Execution time: 662.790 s

Quite interesting this huge difference between both. In any case, this feature to build packages is really awesome, haven't tried yet but I assume if i was going to use these extension modules I'd get rid of those `662.790s` or `822.417s` from the total building and that is... awesome.

One last thing Kay, this [option](https://msdn.microsoft.com/en-us/library/67wc07b9.aspx) should work to move out the .lib & .exp, I recall I've used in the past and I think it worked fine, ie: "/IMPLIB:%{build_path}s\\%{module_name}s.lib"

**Comment by kayhayen** [comment] 2018-09-07 15:44
@brupelo That is compilations times, right? I expect that current "develop" which is going to be 0.5.32.8 to be faster due to using "goto generators". I am surprised that Python3 is faster. Nuitka generates far worse code for that. Thanks for the /IMPLIB hint, taking note of that in my git to try on return. I am travelling tomorrow. Or maybe you could even do a PR with that option added? You know now how to do it. :)

**Comment by brupelo** [comment] 2018-09-07 16:06
@kayhayen Kay, yeah, just compilation times (import detection, tree generation, compilation.... no freezing at all). 

And yeah, about the /IMPLIB i could try to create a PR with that one, shouldn't take me more than... 15min (optimistic mode lol)?  I'd really like to get more involved in the project to create some cool PRs... in fact, if I had 2 weeks of spare time I'd make a whole refactoring of the project to sanitize it a bit (ie: decoupling options as well as making all the subsystems "standalone" ones so they could be tested in isolation more easily)... Thing is, I've already got few dozens if not hundred personal projects I need to handle so it's really difficult to find spare time to spend with these hobby projects, even if Nuitka is one of my favourite python projects out there hehe. Each time i find some few minutes I try to mess around here and there and getting more familiar with the code, you can already say by the ammount of text I've being putting these last days on github... Hehe ;D

**Comment by baizi2k** [comment] 2018-09-08 01:57
It works for me. Thank you guys.

**Comment by brupelo** [comment] 2018-09-09 14:43
IMHO the best solution for this one is nuitka detecting in a smart way the meaning of the positional arg used with `--module`, user should be able to either specify an absolute path poiting out to a .py file or a module name and nuitka should be handle to handle it no matter what, ie:

    def get_package_path(filename):
        package_name = Path(filename).stem
        cmd = ["python", "-c", "import {}; print({}.__file__)".format(package_name, package_name)]
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            shell=True,
            cwd=Path("c:\\")
        )
        (out, err) = proc.communicate()
        return Path(out.decode("utf-8").strip().split("\n")[-1])


    # And then just ...
    if Path(positional_arg).exists():
        nuitka_args = ["--module", str(positional_arg)] + c.dll
    else:
        package_path = get_package_path(positional_arg)
        if package_path.is_file():
            package_path = package_path.parent

        nuitka_args = [
            "--include-package={}".format(positional_arg),
            "--module",
            str(package_path)
        ]

Havent' tested the code but that should give you an idea of what I mean here, and of course. If nuitka wasn't able to automatically figure out what the user meant, report the error back. And yeah, case-sensitivity ftw :D

**Comment by kayhayen** [comment] 2018-09-09 19:32
When executing a Python program, you specify a filename, and implicitly a directory to add to the import search path, where the file lives. I think there is also something funny going on for symlinks, to resolve where they point to, and add that instead or additionally.

When executing a Python package oder module you normally have to go "python -m package_name", and to use it in your program, "import package_name", and for it to work, the import path must be properly set up already.

That said, I am kind of used to providing the filename and detecting it from there, but it violates the principle that the environment must match and leads to ugly results, when e.g. the top level of a package is specified by filename, but then the instruction to include below it, does refer to the names of things.

That is why I want to go with names for everything that is module or package. Temporarily adding to the PYTHONPATH is not an as good idea, because comparing with CPython standard behavior is only going to be different.

So maybe I am all wrong there, and will be flamed once this change comes. But maybe it will just make it way more easy to understand what is going on for people.

Plus, I think a `--package` mode of operation that is needed. However I am totally lacking the time to implement this. The current state of affairs works roughly well enough. The bug at hand here, ist just one that needs to be fixed anyway.

**Comment by brupelo** [comment] 2018-09-09 21:01
Ok, let me talk about some points I consider important here,  even if I haven't been asked to :) , at the end of the day is your call and I understand you'll do what works better for you, which of course I understand and I think IS the right thing to do. I mean, if I open-sourced one of my many projects I'd do the same and while i'd try to be quite open to people's suggestions so the overall project/community would benefit from it I'd be the one making the final calls, not because I'd like to be a "benevolent dictator :D" but because I'd be in a best position to make the calls than other people who didn't architect the system.

That said, I think one of the "big" problems there is right now with nuitka (now I've got more or less a rough idea about the big picture) is sometimes some parts are trying to do too much by themselves, let me elaborate upon this for a bit with some spread ideas in few bulletpoints (although maybe this should go into another issue? dunno):

 - You/we should refactor the whole project so the subsystems will have a much better clear separation of concerns and become less coupled/entangled between them, what do I mean by this? While it's great the extensive test suite you've come up with over the years (this is fantastic and really necessary to deliver high-quality products) I don't see how the different subsystems can be tested very easily in isolation right now. A good subsystem should be testable in isolation and also should be easy enough to be integrated by different apps/tools.

 - The current CLI tool (what it's called nuitka) is doing too much by itself and I think it should be possible to write alternative tools by using the core (i call core to the set of the existing subsystems used by mainControl). I already talked about this in past issues but I feel like repeating myself once more :).

The reality is end-users don't care about developer options in the UI, period. Right now the current CLI is intended to be more a developer tool to test nuitka rather than a tool to be used by casual python developers, so what's the solution? Refactor the project so writing CLIs on top of nuitka core becomes easy.

 - I think a big first step to do so would be decoupling Options module across the whole project, once that's been done, nobody will flame you if eventually you tweak the CLI in a way than people don't like it. 

Why? Well, cos in that case people will have alternatives to write their own apps (be it CLI or or GUI)! So if somebody complains you'll be able to answer "Nuitka core is easily reusable, so if you don't like how the current CLI is presented, you can write another tool that suits you better". 

But... you could argue here than isn't the main goal of the whole project, right? 1 single CLI, right? Well, this wouldn't be just to overengineer the system creating unexistent use-cases but more like allowing people to test the different subsystems or integrate them easily on their tests/tools, by doing so you're giving people the chance to make better bug reports to the upstream, more testing,  more contributors and at the end of the day that will mean the whole project will progress in a faster pace.

 - Problem is sometimes when a project has been developed by 1 single person over many years without getting feedback/reviews/refactorings very often from other developers (or not reviews at all) it's easy than the whole system becomes a [big ball of mud](https://en.wikipedia.org/wiki/Big_ball_of_mud)... and don't get me wrong, that's just a normal thing to happen (even if the coder has a lot of experience and is talended), and that doesn't mean the code itself isn't good enough, it just means it definitely needs to be sanitized so it will become more "friendly/open" to the outside world :) . Does it make sense or just talking nonsense?

Let me tell you a little kind of similar story, few years ago I was working for this company and I'd developed a little 3d engine for them... I'd created a whole engine by myself after many months of developing with very little feedback of my coworkers about the code (just feedback about the visuals and use-cases). At one point, the system was ready to go into production, the code contained really good ideas and it was quite performant but the architecture itself had become a big ball of mud, that project wasn't as large as this project but hey, it wasn't little either, i recall it was like ~2mb of code (excluding static data and 3rd party libraries) so it wasn't a toy project neither. 

I had written the whole engine plus a bunch of tools/tests on top of it and I believed the final result was ready to go, in fact, it was... the visuals were much better than the previous engine used by that company and I was proud of myself of the job done. When it was time to integrate it on production and other teams (placed in different countries) wanted to integrate the whole thing the problems started appearing... the architecture wasn't as simple to use as I thought it was and the system would need quite a lot of sanitization/refactoring. 

The moral of the story? It was just the natural way of software evolution :) . I know from experience when you've coded a project and you already got a clear roadmap/milestones in mind it is really annoying to spend time doing refactoring... but believe me, usually that pays off.

Why? Coming up with a system where you can DELEGATE work to other people IS the KEY... That's what large systems aspire to achieve, allowing TEAM SPLITTING :)

Anyway, i know my opinion wasn't asked  here but as I told you once, I'm a big fan of discussing software architecture topics... So hopefully I've brought to the table some stuff you can think more about ;D

**Comment by kayhayen** [comment] 2018-09-09 21:54
@brupelo I feel this content is misplaced in this issue. I enjoy discussions too, esp. if they have substance and are concrete. I would love to see and discuss based on commits achieving these goals. However, this should happen in the issues intended for it, limited to one specific issue, and if it's general on the mailing list. There I have frequently explained my stance on how I develop Nuitka.

**Comment by kayhayen** [comment] 2018-09-11 07:08
Meh, I just came across this error, trying to reproduce it, which I have so far failed. I noticed how @baizi2k compiled in the OpenGL package directory, and low and behold, for me that causes Nuitka to want to include "OpenGL.build" into the package, which is a bug by itself, triggering an assertion of modules/packages, to not have "." in their name.

Obviously that is a bug by itself, Nuitka will stop considering directories as namespace packages, if they have a "." in their name. Could affect real Python projects on Python3, but it wasn't reported yet, so it surely isn't too common.

I was getting this however:

> /c/Python37_32/lib/site-packages
> $ /c/Python37_32/python ~/repos/Py2C/bin/nuitka --module OpenGL --include-package openGL
> Error, failed to locate package 'openGL'.

Checking with Python 2.7 now which I realized now is what @baizi2k used, I am unable to get the error you have seen. Something about your report is inconsistent, because I am getting file not found error, were I to go into the OpenGL folder as you described.

This leaves me with guessing, what the difference could be. I guess something "dirname" gives empty on things in the current directory, and that is not the proper path. I hate it when that happens. Got to audit that part of code, but a better reproducer would definitely help.

Yours,
Kay

**Comment by kayhayen** [comment] 2018-09-11 07:18
@baizi2k Could you please paste the output of the failing command with --explain-imports option used?

That should help me recognize what is going on for you. It seems to be way more specific for your system that initially thought.

**Comment by kayhayen** [comment] 2018-09-11 07:32
So I think having an empty element in the search path could cause this. Then for candidate selection, if via that search path it was found, it is listed, and used. I wonder how to get that. My attempts with PYTHONPATH didn't give me that, I think there is normally stuff in "site.py" which actively prevents it.

But that actually must be what is going on, no dirname is ever done. The only root of that could be our own getPackageSearchPath(package_name) which does this for non-packages:

`return [os.getcwd(), main_path] + sys.path`

Of these 2 there, maybe main_path could become empty, and that would come from this here:

```
    # Inform the importing layer about the main script directory, so it can use
    # it when attempting to follow imports.
    Importing.setMainScriptDirectory(
        main_dir = os.path.dirname(os.path.abspath(filename))
    )
```

So I am not seeing how the "abspath" one level up would be empty for you, nor the "os.getcwd()", so this must be your "sys.path" in that case.

**Comment by baizi2k** [comment] 2018-09-12 02:19
@kayhayen  sorry for reply late, I'm busing on some project. copy from the prompt:
`
C:\python27-x64\Lib\site-packages>python -m nuitka --module OpenGL --include-package=openGL --explain-imports
findModule: Enter to search 'openGL' in package None level 0.
_findModule: Enter to search 'openGL'.
_findModuleInPath: Enter openGL in None
_findModuleInPath: Using search path ['C:\\python27-x64\\Lib\\site-packages', 'C
:\\python27-x64\\Lib\\site-packages', '', 'C:\\Windows\\system32\\python27.zip',
 'C:\\python27-x64\\DLLs', 'C:\\python27-x64\\lib', 'C:\\python27-x64\\lib\\plat
-win', 'C:\\python27-x64\\lib\\lib-tk', 'C:\\python27-x64', 'C:\\python27-x64\\l
ib\\site-packages'] for None
Candidates OrderedSet([('C:\\python27-x64\\Lib\\site-packages', 1, 'C:\\python27
-x64\\Lib\\site-packages\\openGL'), ('', 1, 'openGL')])
Traceback (most recent call last):
  File "C:\python27-x64\Lib\site-packages\nuitka\__main__.py", line 218, in <mod
ule>
    main()
  File "C:\python27-x64\Lib\site-packages\nuitka\__main__.py", line 212, in main

    MainControl.main()
  File "nuitka\MainControl.py", line 800, in main
    filename = filename
  File "nuitka\MainControl.py", line 123, in createNodeTree
    warn           = False
  File "nuitka\importing\Importing.py", line 281, in findModule
    module_name = module_name,
  File "nuitka\importing\Importing.py", line 514, in _findModule
    module_search_cache[key] = _findModule2(module_name)
  File "nuitka\importing\Importing.py", line 544, in _findModule2
    package_name = package_part
  File "nuitka\importing\Importing.py", line 470, in _findModuleInPath
    search_path = search_path
  File "nuitka\importing\Importing.py", line 387, in _findModuleInPath2
    for fullname, _filename in listDir(candidate[0]):
  File "nuitka\utils\FileOperations.py", line 78, in listDir
    os.listdir(path)
WindowsError: [Error 3] The system cannot find the path specified: ''
`

**Comment by kayhayen** [comment] 2018-09-12 06:33
Yes, indeed there is '' right in your search path. From the position of it, it's my guess that it should be your "site.py" that did this, but we are not going to care about that. However, if that were not there, and it's not for me, I have "." there, which is the valid path item.

I need to locate where Nuitka failed to properly convert `sys.path` to the search path, where "" needs to be treated explicitly.

Then I will try and include it in the next release, but there is no urgency, since we have a workaround for you already that is well, workable. :)

**Comment by kayhayen** [comment] 2018-09-12 06:54
@baizi2k so I pushed the fix to factory for now, you are free to try it, but I don't think it's really needed, the fix was very straightforward.

http://nuitka.net/doc/factory.html

**Closed by kayhayen** 2018-09-12 06:54 UTC
Labels: bug, factory

**Comment by baizi2k** [comment] 2018-09-12 09:34
@kayhayen  Thank you very much. Nuitka is amazing.
