### ISSUE TITLE
Error when running compile application "missing TLS CA certificate"

### ISSUE THREAD

**Issue by BenTearzz** [kayhayen/Nuitka#144] opened 2018-09-21 14:49 UTC
Nuitka: 0.5.33
Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\python.exe
OS: Windows
Arch: x86_64

After compiling my application, when I run it, I get the error: `Could not find a suitable TLS CA certificate bundle, invalid path: D:\Projects\Python Projects\MobilePayAlerts\MPA\Qt\MobilePayAlerts.dist\certifi\cacert.pem`

I've found a related issue on the GitHub for the `requests` module. ([Link](https://github.com/requests/requests/issues/4171#issuecomment-316538822)) After compiling with Nuitka, the folder `...Lib\site-packages\certifi` hasn't been copied over to the **.dist** folder. When I copied the folder "certifi" over it fixed the issue.

So it seems like it's the requests module that's the problem. I only use `requests.post()` in my script.

I'll try to give more detail later as I don't have time right now.

**Comment by kayhayen** [comment] 2018-09-21 15:14
It must be requests that is using certifi under some circumstances. It is indeed a duplicate of #46 for Nuitka, which is not yet fixed, because I didn't get to it. However, requests seems rather important user of it. A minimal reproducer would have been appreciated, but I believe it is not strictly needed. I will try and add that to the data files plugin, so it's automatic.

**Comment by kayhayen** [comment] 2018-09-21 15:16
That is an actually rather strange thing in that is has no code or what, just provides a data file, how bizarre is that.

**Comment by kayhayen** [comment] 2018-09-21 15:39
Factory branch has the fix, needed to add something that makes it possible to put outside of the package itself. Beware, factory has UI changes.

**Closed by kayhayen** 2018-09-21 15:39 UTC
Labels: duplicate
